export enum AccessControlRole {
    ADMIN = 'ADMIN',
    EMPLOYEE = 'EMPLOYEE',
    EMPLOYEE_MANAGER = 'EMPLOYEE_MANAGER',
    EMPLOYEE_AGENT = 'EMPLOYEE_AGENT',
    EMPLOYEE_DRIVER = 'EMPLOYEE_DRIVER',
    CUSTOMER = 'CUSTOMER'
}